# Generated by Django 3.1 on 2021-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
