# Generated by Django 3.1 on 2021-01-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210118_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
