# Generated by Django 3.1 on 2020-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_customer_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
