# Generated by Django 3.1 on 2021-02-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210124_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
